# bot_image.py
# Author: Generated by Claude
# Version: 1.0.0
# Date: 2025-03-01
# Description: Render HTML templates to images using Jinja2 and html2image

import os
import io
import discord
from datetime import datetime
from jinja2 import Environment, FileSystemLoader
from html2image import Html2Image
from PIL import Image

# Get the directory where this file is located
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Setup Jinja2 environment
env = Environment(loader=FileSystemLoader(SCRIPT_DIR))

def render_template_to_image(template_name, context=None):
    """Render a Jinja2 template to an image using html2image
    
    Args:
        template_name (str): The name of the template file
        context (dict): The context data to render the template with
        
    Returns:
        io.BytesIO: A buffer containing the image data
    """
    if context is None:
        context = {}

    # Add default context values
    if 'updated' not in context:
        context['updated'] = datetime.now().strftime("%d/%m/%Y %H:%M")

    # Load template
    template = env.get_template(template_name)
    
    # Render template with context
    html_content = template.render(**context)
    
    # Load CSS content directly
    css_path = os.path.join(SCRIPT_DIR, 'table.css')
    with open(css_path, 'r', encoding='utf-8') as css_file:
        css_content = css_file.read()
    
    # Define scale factor (2x for retina-like quality)
    scale_factor = 1.5
    
    # Add CSS to force crisp font rendering and scale content
    css_with_crisp_fonts = css_content + f"""
    * {{
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-rendering: optimizeLegibility;
    }}
    html, body {{
        width: {796}px;
        margin: 0 auto;
        transform-origin: top left;
        transform: scale(1);
        min-height: 100%;
        height: auto !important;
    }}
    .container {{
        width: 100%;
        height: auto;
        overflow: visible;
    }}
    """
    
    # Inject CSS directly into HTML instead of linking to it
    html_with_css = html_content.replace(
        '<link rel="stylesheet" href="table.css" type="text/css">',
        f'<style>\n{css_with_crisp_fonts}\n</style>'
    )
    
    # Create html2image instance with quality settings
    hti = Html2Image(
        output_path=os.path.join(SCRIPT_DIR, 'tmp'),
        custom_flags=[
            f'--force-device-scale-factor={scale_factor}',
            '--hide-scrollbars',
            '--disable-overflow-hidden=true'
        ]
    )
    
    # Create temporary directory for output
    tmp_dir = os.path.join(SCRIPT_DIR, 'tmp')
    os.makedirs(tmp_dir, exist_ok=True)
    
    # Calculate dimensions - use much taller height to ensure all content is captured
    width = 796
    height = 1000  # Even taller to capture all content
    
    # Take screenshot with higher device scale factor
    screenshot = hti.screenshot(
        html_str=html_with_css,
        save_as='screenshot.png',
        size=(width, height)  # Base size - will be multiplied by device scale factor
    )
    
    # Get the full path to the saved image (first item in returned list)
    image_path = screenshot[0]
    
    # Process the image to 16:9 aspect ratio
    with Image.open(image_path) as img:
        # Calculate target dimensions (16:9 aspect ratio)
        target_width = width
        target_height = int(width * 3 / 2.8)  # 16:9 aspect ratio
        
        # Resize to fit width while maintaining aspect ratio
        img_width, img_height = img.size
        
        # If the image is taller than needed, crop it to the top portion
        if img_height > target_height:
            # Crop to the top portion (most important content)
            img = img.crop((0, 0, img_width, target_height))
        else:
            # If the image is shorter than needed, resize it to fit
            new_height = target_height
            img = img.resize((target_width, new_height), Image.LANCZOS)
        
        # Save to buffer
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        buffer.seek(0)
    
    # Clean up temporary file
    try:
        os.remove(image_path)
    except:
        pass
        
    return buffer

def render_system_data(system_data):
    """Render system data to an image
    
    Args:
        system_data (dict): System data from the API
        
    Returns:
        io.BytesIO: A buffer containing the image data
    """
    # Prepare data for the template
    context = {
        'system_name': system_data['name'],
        'updated': datetime.now().strftime("%d/%m/%Y %H:%M"),
        'population': f"{system_data['population']:,}" if system_data.get('population') else 'None',
        'controllingPower': system_data.get('controllingPower', 'None'),
        'powerState': system_data.get('powerState', 'None'),
        'systemState': system_data.get('systemState', 'None'),
    }
    
    # Get CSS class for the controlling power if it exists
    power_class = ""
    if context['controllingPower'] and context['controllingPower'] != 'None':
        # Extract last name for the CSS class
        power_parts = context['controllingPower'].split()
        if len(power_parts) > 1 and "-" in context['controllingPower']:
            # For hyphenated names like "Lavigny-Duval"
            power_class = context['controllingPower'].split()[-1].lower()
        else:
            # For regular names, take the last part
            power_class = power_parts[-1].lower()
    
    context['power_class'] = power_class
    
    # Process powers list to include CSS classes
    powers_with_classes = []
    raw_powers = system_data.get('powers', [])
    for power in raw_powers:
        power_parts = power.split()
        if len(power_parts) > 1 and "-" in power:
            # For hyphenated names like "Lavigny-Duval"
            css_class = power.split()[-1].lower()
        else:
            # For regular names, take the last part
            css_class = power_parts[-1].lower()
        powers_with_classes.append({
            'name': power,
            'css_class': css_class
        })
    
    context['powers_with_classes'] = powers_with_classes
    context['stations'] = system_data.get('stations', [])
    
    # Render template to image
    return render_template_to_image('table_template.html', context)

async def send_system_image(channel, system_data):
    """Send system data as an image to a Discord channel
    
    Args:
        channel: Discord channel to send the image to
        system_data (dict): System data from the API
    """
    # Render image
    image_buffer = render_system_data(system_data)
    
    # Create file object from buffer
    file = discord.File(fp=image_buffer, filename=f"{system_data['name']}.png")
    
    # Send image to channel
    await channel.send(file=file)
